// Generated by CoffeeScript 1.6.3
(function() {
  var dyna;

  dyna = this.dyna;

  dyna.confirmIdentity = function(e, t) {
    var f;
    console.log('dynaConfirmIdentity');
    f = t.firstNode || e.target.form;
    dyna.valid = $(f).find('input#identity').parsley('validate');
    dyna.valid = dyna.valid || $(f).find('input.identity').parsley('validate');
    if (!dyna.valid) {
      b3.flashError('invalid: ' + e.target.value);
      return dyna.nextStep();
    } else {
      if (dyna.emailMaybe === e.target.value) {
        if (Session.equals('dynaStep', 2)) {
          b3.flashSuccess(e.target.value, {
            header: 'Matched:',
            single: 'dynaUser'
          });
          b3.flashInfo('Please enter a password.', {
            header: "",
            single: 'dynaPass'
          });
          Session.set('dynaStep', 3);
          return dyna.nextStep();
        }
      } else {
        b3.flashWarn(e.target.value, {
          header: dyna.emailMaybe + '- should match -',
          single: 'dynaUser'
        });
        return dyna.nextStep();
      }
    }
  };

}).call(this);
