// Generated by CoffeeScript 1.6.3
(function() {
  var dyna, throttlingTimeout,
    _this = this;

  console.log('dynaSign');

  dyna = this.dyna;

  dyna.confirmed = false;

  throttlingTimeout = 0;

  dyna.resetThrottle = function() {
    dyna.defaultLapse = 4321;
    dyna.lastStamp = 0;
    dyna.averageLapse = 0;
    dyna.keyCount = 0;
    dyna.difLapse = 0;
    dyna.difTotal = 0;
    return dyna.calculatedLapse = dyna.defaultLapse;
  };

  dyna.inputThrottle = function(e, t, cb) {
    var atat, click, i, lapse, stamp, str;
    if (throttlingTimeout !== 0) {
      clearTimeout(throttlingTimeout);
    }
    stamp = new Date().getTime();
    if (dyna.keyCount++ === 0) {
      dyna.firstStamp = stamp;
      return;
    }
    dyna.difLapse = stamp - dyna.lastStamp;
    dyna.lastStamp = stamp;
    dyna.difTotal = stamp - dyna.firstStamp;
    dyna.averageLapse = dyna.difTotal / dyna.keyCount;
    str = e.target.value;
    if (str == null) {
      click = true;
      i = t.find('input');
      str = $(i).val();
    }
    atat = str.indexOf("@");
    if (atat < (dyna.keyCount - 1)) {
      if (atat > -1) {
        dyna.calculatedLapse = 2 * dyna.defaultLapse;
      }
      if (atat = -1) {
        dyna.calculatedLapse = dyna.defaultLapse;
      }
    }
    if (atat === (dyna.keyCount - 1)) {
      dyna.calculatedLapse = 2 * dyna.defaultLapse;
    }
    if (/\.com/.test(str) || /\.org/.test(str) || /\.net/.test(str) || /\.io/.test(str) || /\.me/.test(str) || /\.edu/.test(str)) {
      dyna.calculatedLapse = 100;
    }
    switch (e.keyCode) {
      case 13:
        lapse = 100;
        break;
      case 8:
      case 37:
      case 39:
        console.log('backup');
        dyna.resetThrottle();
        dyna.keyCount = 1;
        lapse = 4321;
        break;
      default:
        lapse = dyna.calculatedLapse;
    }
    if (click) {
      lapse = 100;
    }
    return throttlingTimeout = setTimeout(function() {
      return cb(e, t);
    }, lapse);
  };

}).call(this);
