// Generated by CoffeeScript 1.6.3
(function() {
  Meteor.methods({
    checkIdentity: function(email) {
      var user;
      console.log('checkidentity', email);
      if (Meteor.isServer) {
        user = Meteor.users.findOne({
          'emails.address': email
        });
        if (user != null) {
          return user;
        } else {
          return false;
        }
      }
      return false;
    },
    sendVerificationEmail: function(email) {
      var id, u;
      if (Meteor.isServer) {
        if (Meteor.userId()) {
          id = Meteor.userId();
        } else {
          u = Meteor.users.findOne({
            'emails.address': email
          });
          id = u._id;
        }
        console.log('sending verification email', id, email);
        return Accounts.sendVerificationEmail(id, email);
      }
    }
  });

}).call(this);
