// Generated by CoffeeScript 1.6.3
(function() {
  var dynaLogin, logInTimeout, _dynaLogin;

  logInTimeout = 0;

  this.dynaLogin = dynaLogin = function(email, password) {
    if (Meteor.userId()) {
      return;
    }
    if (Meteor.loggingIn()) {
      return;
    }
    this.email = email;
    this.password = password;
    if (logInTimeout !== 0) {
      clearTimeout(logInTimeout);
    }
    return logInTimeout = setTimeout(_dynaLogin, 1000);
  };

  _dynaLogin = function() {
    var email, password,
      _this = this;
    email = dynaLogin.email;
    password = dynaLogin.password;
    return Meteor.loginWithPassword(email, password, function(error) {
      if (error != null) {
        Session.set('dynaTooltipText', error.reason);
        b3.flashError(error.reason, {
          header: 'Login Error:',
          single: 'dynaPass'
        });
        return Session.set('dynaUserAuthenticated', false);
      } else {
        b3.flashSuccess(email, {
          header: 'Authenticated:',
          single: 'dynaPass'
        });
        return Session.set('dynaStep', 0);
      }
    });
  };

}).call(this);
