// Generated by CoffeeScript 1.6.3
(function() {
  Router.map(function() {
    this.route('verifyAccount', {
      path: '/verify-email/:token',
      action: function() {
        var token;
        token = this.params.token;
        console.log('verify-email token', token);
        return Accounts.verifyEmail(token, function(error) {
          if (error != null) {
            console.log('error', error, token);
            b3.flashError(error.reason);
          } else {
            b3.flashSuccess('Account e-mail verification complete.');
          }
          return Router.go('/');
        });
      }
    });
    return this.route('resetPassword', {
      path: '/reset-password/:token',
      action: function() {
        Session.set('dynaToken', this.params.token);
        Session.set('dynaStep', 'reset');
        Session.set('dynaPasswordTooltip', 'Enter a new password.');
        return b3.flashInfo('Please enter a new password.');
      }
    });
  });

}).call(this);
