// Generated by CoffeeScript 1.6.3
(function() {
  var dyna;

  dyna = this.dyna;

  dyna.inputPassword = function(e, t) {
    var email, f, msg, valid;
    e.preventDefault();
    if (e.target.id !== 'passwordInput') {
      return;
    }
    if (e.keyCode === 13) {
      return this.signPass(e, t);
    }
    f = t.firstNode || e.target.f;
    valid = $(f).find("input#passwordInput").parsley('validate');
    if (valid) {
      Session.set('dynaPasswordTooltip', 'password valid');
      if (Session.equals('dynaUserExisting', true)) {
        email = Session.get('dynaEmailMaybe');
        return this.dynaLogin(email, e.target.value);
      }
    } else {
      msg = "Password: ";
      if (e.target.value.length < 6) {
        msg += '- min. 6 characters';
      }
      if (!/\d/.test(e.target.value)) {
        msg += '- min. 1 number ';
      }
      if (!/\D/.test(e.target.value)) {
        msg += '- min. 1 letter';
      }
      Session.set('dynaPasswordTooltip', msg);
    }
    return false;
  };

}).call(this);
