// Generated by CoffeeScript 1.6.3
(function() {
  var dyna;

  dyna = this.dyna;

  dyna.signUpNew = function(e, t) {
    var $f, email, f, hasError, password, profile, _ref, _ref1, _ref2;
    hasError = false;
    e.preventDefault();
    f = ((_ref = t.firstNode) != null ? _ref.form : void 0) || ((_ref1 = e.target) != null ? _ref1.form : void 0);
    $f = $(f);
    password = $f.find('input').val();
    console.log('dyna', dyna);
    email = dyna.emailMaybe;
    profile = (((_ref2 = dyna.accounts) != null ? _ref2.profile : void 0) != null) || {};
    console.log('creating user', email, password, profile);
    Accounts.createUser({
      email: email,
      password: password,
      profile: profile
    }, function(error) {
      if (error != null) {
        b3.flashError(error.reason, {
          single: 'dynaPass'
        });
        Session.set('dynaStep', 3);
        return dyna.nextStep();
      } else {
        b3.flashSuccess('Welcome! Thanks for signing up.');
        b3.flashInfo("A verification e-mail should be delivered to " + email + " shortly.");
        Meteor.call('sendVerificationEmail', email);
        Session.set('dynaStep', 5);
        return dyna.nextStep();
      }
    });
    if (Session.equals('dynaStep', 1)) {
      dyna.emailMaybe = $f.find('input.identity').val();
      b3.flashInfo(dyna.emailMaybe, {
        header: 'Please confirm e-mail:',
        single: 'dynaUser'
      });
      Session.set('dynaStep', 2);
    }
    return dyna.nextStep();
  };

}).call(this);
